---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	user_interaction(user_interaction)
	admin_approval(admin_approval)
	data_recording(data_recording)
	__end__([<p>__end__</p>]):::last
	__start__ --> user_interaction;
	admin_approval -. &nbsp;end&nbsp; .-> __end__;
	admin_approval -.-> data_recording;
	user_interaction -. &nbsp;end&nbsp; .-> __end__;
	user_interaction -.-> admin_approval;
	data_recording --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
